## Single neuron 

In [1]:
inputs = [1,2,3,2.5]
weights= [0.2,0.8,-0.5,1.0]

In [2]:
bias = 2

In [3]:
outputs = inputs[0]*weights[0]+inputs[1]*weights[1]+inputs[2]*weights[2]+inputs[3]*weights[3]+bias

In [4]:
outputs

4.8

## Three neuron with four input

In [5]:
inputs = [1,2,3,2.5]
weights1= [0.2,0.8,-0.5,1.0]
weights2= [0.5,-0.91,0.26,-0.5]
weights3= [-0.26,-0.27,0.17,0.87]

In [6]:
bias1= 2
bias2= 3
bias3= 0.5

In [7]:
outputs = [inputs[0]*weights1[0]+inputs[1]*weights1[1]+inputs[2]*weights1[2]+inputs[3]*weights1[3]+bias1,
           inputs[0]*weights2[0]+inputs[1]*weights2[1]+inputs[2]*weights2[2]+inputs[3]*weights2[3]+bias2,
           inputs[0]*weights3[0]+inputs[1]*weights3[1]+inputs[2]*weights3[2]+inputs[3]*weights3[3]+bias3]

In [8]:
outputs

[4.8, 1.21, 2.385]

In [9]:
inputs = [1,2,3,2.5]
weights= [[0.2,0.8,-0.5,1.0],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]

In [10]:
biases= [2,3,0.5]


In [11]:
# using for loop
layer_outputs= []
for neuron_weights, neuron_bias in zip(weights,biases):
    neuron_output=0 # output of given neurons
    for n_input, weight in zip(inputs,neuron_weights):
        neuron_output += n_input*weight
    neuron_output +=neuron_bias
    layer_outputs.append(neuron_output)   

In [12]:
layer_outputs

[4.8, 1.21, 2.385]

In [13]:
#numpy
#dot product, multiply elementwise 
import numpy as np
output = np.dot(weights, inputs) + biases
outputs

[4.8, 1.21, 2.385]

In [14]:
np.shape(inputs)

(4,)

In [15]:
np.shape(weights)

(3, 4)

In [16]:
output = np.dot(inputs, weights) + biases

ValueError: shapes (4,) and (3,4) not aligned: 4 (dim 0) != 3 (dim 0)

## Batch ,layer , object 

In [17]:
import numpy as np 

np.random.seed(0)

In [18]:
inputs = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [19]:
weights= [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]

In [20]:
biases = [2,3,0.5]

In [21]:
np.shape(inputs), np.shape(weights), np.shape(biases)

((3, 4), (3, 4), (3,))

In [22]:
output = np.dot(inputs, np.array(weights))+biases
output

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [23]:
output = np.dot(inputs, np.array(weights).T)+biases
output

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [24]:
## two layer

In [25]:
#first layer
inputs = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

weights= [[0.2,0.8,-0.5,1.0],
          [0.5,-0.91,0.26,-0.5],
          [-0.26,-0.27,0.17,0.87]]
biases = [2,3,0.5]

In [26]:
#second layer wesights
weights2= [[0.1,0.14,0.5],
          [-0.5, 0.12, -0.33],
          [-0.44, 0.73,-0.13]]
biases2= [-1, 2, -0.5]

In [27]:
layer1_outputs= np.dot(inputs, np.array(weights).T)+biases
layer2_outputs= np.dot(layer1_outputs, np.array(weights2).T)+biases2
layer2_outputs

array([[ 0.8419 , -1.04185, -2.03875],
       [-0.2634 , -2.7332 , -5.7633 ],
       [-0.69886,  1.41254, -0.35655]])

In [28]:
#oops 
np.random.seed(0)
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]

In [29]:
class Layer_Dense:
    def __init__(self,n_inputs,n_neurons):
        self.weights= 0.10*np.random.randn(n_inputs, n_neurons)
        self.biases= np.zeros((1,n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs,self.weights)+self.biases

In [30]:
Layer1 = Layer_Dense(4,5)
Layer2= Layer_Dense(5,2)

In [31]:
Layer1.forward(X)
print(Layer1.output)

[[ 0.10758131  1.03983522  0.24462411  0.31821498  0.18851053]
 [-0.08349796  0.70846411  0.00293357  0.44701525  0.36360538]
 [-0.50763245  0.55688422  0.07987797 -0.34889573  0.04553042]]


In [32]:
Layer2.forward(Layer1.output)
print(Layer2.output)

[[ 0.148296   -0.08397602]
 [ 0.14100315 -0.01340469]
 [ 0.20124979 -0.07290616]]


## Hidden Layer activation function 

In [34]:
pip install nnfs

Note: you may need to restart the kernel to use updated packages.


In [35]:
import numpy as np 
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

X, y = spiral_data(100, 3)   

In [37]:
X[1:3]

array([[0.00299556, 0.00964661],
       [0.01288097, 0.01556285]], dtype=float32)

In [38]:
y[1:3]

array([0, 0], dtype=uint8)

In [40]:
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [41]:
class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

In [42]:
layer1 = Layer_Dense(2,5)
activation1 = Activation_ReLU()

In [43]:
layer1.forward(X)

print(layer1.output)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00]
 [ 5.09662132e-05  2.82163121e-04 -6.14295888e-04 -2.78327265e-04
  -2.18806133e-04]
 [-2.53826292e-05  1.32260774e-03 -1.89793913e-03 -1.03709206e-03
  -6.62760111e-04]
 ...
 [ 1.49472691e-02 -1.03460461e-01  1.00327469e-01  6.80047795e-02
   3.40471603e-02]
 [ 1.17370244e-02 -1.04946040e-01  1.14487566e-01  7.24482983e-02
   3.92385311e-02]
 [ 1.57508273e-02 -1.03014432e-01  9.66713205e-02  6.68329149e-02
   3.27085815e-02]]


In [44]:
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [5.09662132e-05 2.82163121e-04 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 1.32260774e-03 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 ...
 [1.49472691e-02 0.00000000e+00 1.00327469e-01 6.80047795e-02
  3.40471603e-02]
 [1.17370244e-02 0.00000000e+00 1.14487566e-01 7.24482983e-02
  3.92385311e-02]
 [1.57508273e-02 0.00000000e+00 9.66713205e-02 6.68329149e-02
  3.27085815e-02]]
