In [1]:
import numpy as np
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import *

Input shape of SimpleRNN should be 3D tensor => (batch_size, timesteps, input_dim)

* Where the first dimension represents the batch size, 

* the second dimension represents the time-steps and 

* the third dimension represents the number of units in one input sequence. For example, the input shape looks like (batch_size, time_steps, units)

![img.png](https://miro.medium.com/max/1064/1*AQKRJsRdWx2HZ85H1yWoKw.png)

In [2]:
# for instance, consider below array
x = np.array([[
             [1,    # => input_dim 1
              2,    # => input_dim 2 
              3],   # => input_dim 3     # => timestep 1                            
             [4, 5, 6]                   # => timestep 2
             ],                                  # => batch 1
             [[7, 8, 9], [10, 11, 12]],          # => batch 2
             [[13, 14, 15], [16, 17, 18]]        # => batch 3
             ])

In [3]:
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [4]:
print('(Batch size, timesteps, input_dim) = ',x.shape)

(Batch size, timesteps, input_dim) =  (3, 2, 3)


In [5]:
# rnn = SimpleRNN(50)(Input(shape = (10,))) => error
# rnn = SimpleRNN(50)(Input(shape = (10, 30, 40))) => error
rnn = SimpleRNN(50)(Input(shape = (10, 30)))
print(rnn.shape)

(None, 50)


##### * That return sequences return the hidden state output for each input time step.

##### * That return state returns the hidden state output and cell state for the last input time step

##### EX: 1

In [6]:
rnn = SimpleRNN(50, return_sequences = True)(Input(shape = (10, 30)))
print(rnn.shape)

(None, 10, 50)


##### EX: 2

In [7]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input,LSTM
# define model
inputs1 = Input(shape=(3, 1))
print(inputs1)
rnn1 = SimpleRNN(1, return_sequences=True)(inputs1)
print(rnn1.shape)

Tensor("input_3:0", shape=(None, 3, 1), dtype=float32)
(None, 3, 1)


In [8]:
model = Model(inputs=inputs1, outputs=rnn1)
# define input data
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

[[[0.10127292]
  [0.1016177 ]
  [0.20049304]]]


* returns a sequence of 3 values, one hidden state output for each input time step for the single LSTM cell in the layer

###### * You must set return_sequences=True when stacking LSTM layers so that the second LSTM layer has a three-dimensional sequence input

* Keras provides the return_state argument to the LSTM layer that will provide access to the hidden state output (state_h) and the cell state (state_c).

In [9]:
# define model
inputs1 = Input(shape=(3, 1))
output , state = SimpleRNN(1, return_state=True)(inputs1)
output.shape, state.shape

(TensorShape([None, 1]), TensorShape([None, 1]))

In [10]:
model = Model(inputs=inputs1, outputs=[output , state])
# define input data
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

[array([[-0.711244]], dtype=float32), array([[-0.711244]], dtype=float32)]


In [11]:
# define model
inputs1 = Input(shape=(3, 1))
lstm1, state_h, state_c = LSTM(1, return_sequences=True, return_state=True)(inputs1)
model = Model(inputs=inputs1, outputs=[lstm1, state_h, state_c])
# define input data
data = np.array([0.1, 0.2, 0.3]).reshape((1,3,1))
# make and show prediction
print(model.predict(data))

[array([[[-0.02369108],
        [-0.06694788],
        [-0.12407959]]], dtype=float32), array([[-0.12407959]], dtype=float32), array([[-0.24914914]], dtype=float32)]


* The layer returns the hidden state for each input time step, then separately, the hidden state output for the last time step and the cell state for the last input time step.(the last value in the returned sequences (first array) matches the value in the hidden state (second array).