## 1 .Collection Module

#### Counter

A counter is a container that stores elements as dictionary keys, and their counts are stored as dictionary values.

In [1]:
from collections import Counter
a = "aaaaabbbbcccdde"
my_counter = Counter(a)
print(my_counter)

Counter({'a': 5, 'b': 4, 'c': 3, 'd': 2, 'e': 1})


In [2]:
print(my_counter.items())
print(my_counter.keys())
print(my_counter.values())

dict_items([('a', 5), ('b', 4), ('c', 3), ('d', 2), ('e', 1)])
dict_keys(['a', 'b', 'c', 'd', 'e'])
dict_values([5, 4, 3, 2, 1])


In [3]:
my_list = [0, 1, 0, 1, 2, 1, 1, 3, 2, 3, 2, 4]
my_counter = Counter(my_list)
print(my_counter)

# most common items
print(my_counter.most_common(1))

# Return an iterator over elements repeating each as many times as its count. 
# Elements are returned in arbitrary order.
print(list(my_counter.elements()))

Counter({1: 4, 2: 3, 0: 2, 3: 2, 4: 1})
[(1, 4)]
[0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 4]


#### namedtuple

namedtuples are easy to create, lightweight object types. They assign meaning to each position in a tuple and allow for more readable, self-documenting code. They can be used wherever regular tuples are used, and they add the ability to access fields by name instead of position index.

In [4]:
from collections import namedtuple
# create a namedtuple with its class name as string and its fields as string
# fields have to be separated by comma or space in the given string
Point = namedtuple('Point','x, y')
pt = Point(1, -4)
print(pt)
print(pt._fields)
print(type(pt))
print(pt.x, pt.y)

Point(x=1, y=-4)
('x', 'y')
<class '__main__.Point'>
1 -4


In [5]:
Person = namedtuple('Person','name, age')
friend = Person(name='Tom', age=25)
print(friend.name, friend.age)

Tom 25


#### OrderedDict

OrderedDicts are just like regular dictionaries but they remember the order that items were inserted. When iterating over an ordered dictionary, the items are returned in the order their keys were first added. If a new entry overwrites an existing entry, the original insertion position is left unchanged. They have become less important now that the built-in dict class gained the ability to remember insertion order (guaranteed since Python 3.7). But some differences still remain, e.g. the OrderedDict is designed to be good at reordering operations.

In [6]:
from collections import OrderedDict
ordinary_dict = {}
ordinary_dict['a'] = 1
ordinary_dict['b'] = 2
ordinary_dict['c'] = 3
ordinary_dict['d'] = 4
ordinary_dict['e'] = 5
# this may be in orbitrary order prior to Python 3.7
print(ordinary_dict)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [7]:
ordered_dict = OrderedDict()
ordered_dict['a'] = 1
ordered_dict['b'] = 2
ordered_dict['c'] = 3
ordered_dict['d'] = 4
ordered_dict['e'] = 5
print(ordered_dict)
# same functionality as with ordinary dict, but always ordered
for k, v in ordinary_dict.items():
    print(k, v)

OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])
a 1
b 2
c 3
d 4
e 5


#### defaultdict

The defaultdict is a container that's similar to the usual dict container, but the only difference is that a defaultdict will have a default value if that key has not been set yet. If you didn't use a defaultdict you'd have to check to see if that key exists, and if it doesn't, set it to what you want.

In [8]:
from collections import defaultdict

# initialize with a default integer value, i.e 0
d = defaultdict(int)
d['yellow'] = 1
d['blue'] = 2
print(d.items())
print(d['green'])

dict_items([('yellow', 1), ('blue', 2)])
0


In [9]:
# initialize with a default list value, i.e an empty list
d = defaultdict(list)
s = [('yellow', 1), ('blue', 2), ('yellow', 3), ('blue', 4), ('red', 5)]
for k, v in s:
    d[k].append(v)

print(d.items())
print(d['green'])

dict_items([('yellow', [1, 3]), ('blue', [2, 4]), ('red', [5])])
[]


#### deque

A deque is a double-ended queue. It can be used to add or remove elements from both ends. 

* Deques support thread safe, memory efficient appends and pops from either side of the deque with approximately the same O(1) performance in either direction. The more commonly used stacks and queues are degenerate forms of deques, where the inputs and outputs are restricted to a single end.

In [1]:
from collections import deque
d = deque()

# append() : add elements to the right end 
d.append('a')
d.append('b')
print(d)

deque(['a', 'b'])


In [2]:
# appendleft() : add elements to the left end 
d.appendleft('c')
print(d)

deque(['c', 'a', 'b'])


In [3]:
# pop() : return and remove elements from the right
print(d.pop())
print(d)

# popleft() : return and remove elements from the left
print(d.popleft())
print(d)

# clear() : remove all elements
d.clear()
print(d)


b
deque(['c', 'a'])
c
deque(['a'])
deque([])


In [4]:
d = deque(['a', 'b', 'c', 'd'])

# extend at right or left side
d.extend(['e', 'f', 'g'])
d.extendleft(['h', 'i', 'j']) # note that 'j' is now at the left most position
print(d)

deque(['j', 'i', 'h', 'a', 'b', 'c', 'd', 'e', 'f', 'g'])


In [5]:
# count(x) : returns the number of found elements
print(d.count('h'))

# rotate 1 positions to the right
d.rotate(1)
print(d)

# rotate 2 positions to the left
d.rotate(-2)
print(d)

1
deque(['g', 'j', 'i', 'h', 'a', 'b', 'c', 'd', 'e', 'f'])
deque(['i', 'h', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'j'])


# 2. Itertools

#### product()

This tool computes the cartesian product of input iterables.
It is equivalent to nested for-loops. For example, product(A, B) returns the same as ((x,y) for x in A for y in B).

In [6]:
from itertools import product

prod = product([1, 2], [3, 4])
print(list(prod)) # note that we convert the iterator to a list for printing

# to allow the product of an iterable with itself, specify the number of repetitions 
prod = product([1, 2], [3], repeat=2)
print(list(prod)) # note that we convert the iterator to a list for printing

[(1, 3), (1, 4), (2, 3), (2, 4)]
[(1, 3, 1, 3), (1, 3, 2, 3), (2, 3, 1, 3), (2, 3, 2, 3)]


#### permutations()

This tool returns successive length permutations of elements in an iterable, with all possible orderings, and no repeated elements.


In [7]:
from itertools import permutations

perm = permutations([1, 2, 3])
print(list(perm))

# optional: the length of the permutation tuples
perm = permutations([1, 2, 3], 2)
print(list(perm))

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]
[(1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2)]


#### combinations() and combinationswithreplacement()
r-length tuples, in sorted order. So, if the input iterable is sorted, the combination tuples will be produced in sorted order. combinations() does not allow repeated elements, but combinationswithreplacement() does.

In [8]:
from itertools import combinations, combinations_with_replacement

# the second argument is mandatory and specifies the length of the output tuples.
comb = combinations([1, 2, 3, 4], 2)
print(list(comb))

comb = combinations_with_replacement([1, 2, 3, 4], 2)
print(list(comb))

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]
[(1, 1), (1, 2), (1, 3), (1, 4), (2, 2), (2, 3), (2, 4), (3, 3), (3, 4), (4, 4)]


#### accumulate()

Make an iterator that returns accumulated sums, or accumulated results of other binary functions.


In [9]:
from itertools import accumulate

# return accumulated sums
acc = accumulate([1,2,3,4])
print(list(acc))

[1, 3, 6, 10]


In [10]:
# other possible functions are possible
import operator
acc = accumulate([1,2,3,4], func=operator.mul)
print(list(acc))

acc = accumulate([1,5,2,6,3,4], func=max)
print(list(acc))

[1, 2, 6, 24]
[1, 5, 5, 6, 6, 6]


#### groupby()

Make an iterator that returns consecutive keys and groups from the iterable. The key is a function computing a key value for each element. If not specified or is None, key defaults to an identity function and returns the element unchanged. Generally, the iterable needs to already be sorted on the same key function.



In [11]:
from itertools import groupby

# use a function as key
def smaller_than_3(x):
    return x < 3

In [13]:
group_obj = groupby([1, 2, 3, 4], key=smaller_than_3)
print(group_obj)
for key, group in group_obj:
    print(key, list(group))

True [1, 2]
False [3, 4]


In [14]:
# or use a lamda expression, e.g. words with an 'i':
group_obj = groupby(["hi", "nice", "hello", "cool"], key=lambda x: "i" in x)
for key, group in group_obj:
    print(key, list(group))

True ['hi', 'nice']
False ['hello', 'cool']


In [15]:
persons = [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25}, 
           {'name': 'Lisa', 'age': 27}, {'name': 'Claire', 'age': 28}]

for key, group in groupby(persons, key=lambda x: x['age']):
    print(key, list(group))

25 [{'name': 'Tim', 'age': 25}, {'name': 'Dan', 'age': 25}]
27 [{'name': 'Lisa', 'age': 27}]
28 [{'name': 'Claire', 'age': 28}]


#### Infinite iterators: count(), cycle(), repeat()

In [16]:
from itertools import count, cycle, repeat
# count(x): count from x: x, x+1, x+2, x+3...
for i in count(10):
    print(i)
    if  i >= 13:
        break

10
11
12
13


In [17]:
# cycle(iterable) : cycle infinitely through an iterable
print("")
sum = 0
for i in cycle([1, 2, 3]):
    print(i)
    sum += i
    if sum >= 12:
        break


1
2
3
1
2
3


In [18]:
# repeat(x): repeat x infinitely or n times
print("")
for i in repeat("A", 3):
    print(i)


A
A
A


# 3. Lambda

A lambda function is a small (one line) anonymous function that is defined without a name. A lambda function can take any number of arguments, but can only have one expression. While normal functions are defined using the def keyword, in Python anonymous functions are defined using the lambda keyword.

##### lambda arguments: expression

They are also used along with built-in functions like 

##### map(), filter(), reduce().

In [19]:
# a lambda function that adds 10 to the input argument
f = lambda x: x+10
val1 = f(5)
val2 = f(100)
print(val1, val2)

15 110


In [20]:
# a lambda function that multiplies two input arguments and returns the result
f = lambda x,y: x*y
val3 = f(2,10)
val4 = f(7,5)
print(val3, val4)

20 35


In [21]:
def myfunc(n):
    return lambda x: x * n

In [22]:
doubler = myfunc(2)
print(doubler(6))

tripler = myfunc(3)
print(tripler(6))

12
18


#### Custom sorting using a lambda function as key parameter

The key function transforms each element before sorting.

In [33]:
points2D = [(1, 9), (4, 1), (5, -3), (10, 2)]
sorted_default = sorted(points2D)
print(sorted_default)
sorted_by_y = sorted(points2D, key= lambda x: x[1])
print(sorted_by_y)

[(1, 9), (4, 1), (5, -3), (10, 2)]
[(5, -3), (4, 1), (10, 2), (1, 9)]


In [26]:
mylist = [- 1, -4, -2, -3, 1, 2, 3, 4]
sorted_by_abs = sorted(mylist, key= lambda x: abs(x))
print(sorted_by_abs)

[-1, 1, -2, 2, -3, 3, -4, 4]


#### Use lambda for map function

map(func, seq), transforms each element with the function.

In [30]:
a  = [1, 2, 3, 4, 5, 6]
print(a)
b = list(map(lambda x: x * 2 , a))

# However, try to prefer list comprehension
# Use map if you have an already defined function
c = [x*2 for x in a]
print(b)
print(c)

[1, 2, 3, 4, 5, 6]
[2, 4, 6, 8, 10, 12]
[2, 4, 6, 8, 10, 12]


#### Use lambda for filter function

filter(func, seq), returns all elements for which func evaluates to True.

In [31]:
a = [1, 2, 3, 4, 5, 6, 7, 8]
b = list(filter(lambda x: (x%2 == 0) , a))

# However, the same can be achieved with list comprehension
c = [x for x in a if x%2 == 0]
print(b)
print(c)

[2, 4, 6, 8]
[2, 4, 6, 8]


#### reduce

reduce(func, seq), repeatedly applies the func to the elements and returns a single value.
func takes 2 arguments.

In [32]:
from functools import reduce
a = [1, 2, 3, 4]
product_a = reduce(lambda x, y: x*y, a)
print(product_a)
sum_a = reduce(lambda x, y: x+y, a)
print(sum_a)

24
10


# 4. Random

This module implements pseudo-random number generators for various distributions

In [34]:
import random

# random float in [0,1)
a = random.random()
print(a)


0.9213500836444136


In [35]:
# random float in range [a,b]
a = random.uniform(1,10)
print(a)

6.850525890162446


In [36]:
# random integer in range [a,b]. b is included
a = random.randint(1,10)
print(a)


4


In [37]:
# random integer in range [a,b). b is excluded
a = random.randrange(1,10)
print(a)

2


In [39]:
# random float from a normal distribution with mu and sigma
a = random.normalvariate(0, 1)
print(a)

-0.48194501968427905


In [40]:
# choose a random element from a sequence
a = random.choice(list("ABCDEFGHI"))
print(a)

A


In [41]:
# choose k unique random elements from a sequence
a = random.sample(list("ABCDEFGHI"), 3)
print(a)

['C', 'H', 'E']


In [42]:
# choose k elements with replacement, and return k sized list
a = random.choices(list("ABCDEFGHI"),k=3)
print(a)

['A', 'D', 'E']


In [43]:
# shuffle list in place
a = list("ABCDEFGHI")
random.shuffle(a)
print(a)

['C', 'A', 'I', 'D', 'B', 'E', 'G', 'H', 'F']


#### The seed generator
With random.seed(), you can make results reproducible, and the chain of calls after random.seed() will produce the same trail of data. The sequence of random numbers becomes deterministic, or completely determined by the seed value.

In [44]:
print('Seeding with 1...\n')

random.seed(1)
print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

Seeding with 1...

0.13436424411240122
8.626903632435095
B


In [45]:
print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))


Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E


In [46]:
print('\nRe-seeding with 1...\n')
random.seed(1)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))

print('\nRe-seeding with 42...\n')
random.seed(42)  # Re-seed

print(random.random())
print(random.uniform(1,10))
print(random.choice(list("ABCDEFGHI")))


Re-seeding with 1...

0.13436424411240122
8.626903632435095
B

Re-seeding with 42...

0.6394267984578837
1.2250967970040025
E


##### The secrets module

The secrets module is used for generating cryptographically strong random numbers suitable for managing data such as passwords, account authentication, security tokens, and related secrets.
In particularly, secrets should be used in preference to the default pseudo-random number generator in the random module, which is designed for modelling and simulation, not security or cryptography.

In [48]:
import secrets

# random integer in range [0, n).
a = secrets.randbelow(10)
print(a)

# return an integer with k random bits.
a = secrets.randbits(5)
print(a)

# choose a random element from a sequence
a = secrets.choice(list("ABCDEFGHI"))
print(a)

0
15
C


#### Random number with numpy

In [49]:
import numpy as np

np.random.seed(1)
# rand(d0,d1,…,dn)
# generate nd array with random floats, arrays has size (d0,d1,…,dn)
print(np.random.rand(3))
# reset the seed
np.random.seed(1)
print(np.random.rand(3))

[4.17022005e-01 7.20324493e-01 1.14374817e-04]
[4.17022005e-01 7.20324493e-01 1.14374817e-04]


In [50]:
# generate nd array with random integers in range [a,b) with size n
values = np.random.randint(0, 10, (5,3))
print(values)

[[5 0 0]
 [1 7 6]
 [9 2 4]
 [5 2 4]
 [2 4 7]]


In [51]:
# generate nd array with Gaussian values, array has size (d0,d1,…,dn)
# values from standard normal distribution with mean 0.0 and standard deviation 1.0
values = np.random.randn(5)
print(values)

[-2.29230928 -1.41555249  0.8858294   0.63190187  0.04026035]


In [52]:
# randomly shuffle a nd array.
# only shuffles the array along the first axis of a multi-dimensional array
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.random.shuffle(arr)
print(arr)

[[4 5 6]
 [7 8 9]
 [1 2 3]]
