##### Bayes’ Theorem provides a way that we can calculate the probability of a piece of data belonging to a given class, given our prior knowledge. Bayes’ Theorem is stated as:

#### P(class|data) = (P(data|class) * P(class)) / P(data)

Where P(class|data) is the probability of class given the provided data.

##### Resource :

* https://machinelearningmastery.com/bayes-theorem-for-machine-learning/

* https://towardsdatascience.com/na%C3%AFve-bayes-from-scratch-using-python-only-no-fancy-frameworks-a1904b37222d

* https://towardsdatascience.com/naive-bayes-classifier-81d512f50a7c

* https://towardsdatascience.com/na%C3%AFve-bayes-from-scratch-using-python-only-no-fancy-frameworks-a1904b37222d

![img.png](https://miro.medium.com/max/605/1*Gb2Ifjn1olE5ML6mqY5WNQ.png)

X as given that 
![img.png](https://miro.medium.com/max/680/1*RFUldC6DTLSQ_8ZEDxDKBQ.png)

![img.png](https://miro.medium.com/max/875/1*y1pZM0oYjQfMJt0rDX-REA.png)

![img.png](https://miro.medium.com/max/875/1*h31gli0qTasplUm6tJJ7ig.png)

Therefore, we need to find the class y with maximum probability.

![img.png](https://miro.medium.com/max/875/1*0AWiuPgpHElcqB2X-fpVkw.png)

##### prior probability(p(y)) : frequency 
##### class conditional probability (p(x_i|y)) : 

![img.png](https://miro.medium.com/max/875/1*0If5Mey7FnW_RktMM5BkaQ.png)

![img.png](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/PDF-log_normal_distributions.svg/1200px-PDF-log_normal_distributions.svg.png)

In [6]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import datasets
import matplotlib.pyplot as plt

In [7]:
import numpy as np

In [8]:
X, y = datasets.make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=123)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=123)

In [11]:
X[:5] , y[:5]

(array([[ 0.24063119, -0.07970884, -0.05313268,  0.09263489, -0.13935777,
          1.20319285, -0.15590018, -0.09709308,  0.06994683,  0.11660277],
        [ 0.75425016, -0.937854  ,  0.21947276, -1.28066902,  1.55618457,
         -0.65538962,  0.77023157,  0.19311463, -2.27886416,  0.65102942],
        [ 0.9584009 , -1.31841143,  1.15350536, -0.96816469,  1.88667929,
          0.53473693,  0.46015911,  0.0423321 ,  0.79249125,  0.24144309],
        [ 0.64384845,  0.35082051, -0.10869679,  0.71060146, -0.85406842,
          0.33485545,  0.60778386,  0.94834854,  1.29778445,  2.16583174],
        [ 1.03268464, -1.26482413,  0.18067775,  0.35989813, -0.26303363,
         -0.33760592,  0.52075594, -1.4403634 ,  1.25766489,  0.14630826]]),
 array([0, 0, 1, 1, 1]))

In [13]:
np.unique(y) # we have two target values 

array([0, 1])

In [17]:
X_c1 =X[y==1] # target 1
X_c2 =X[y==0] #target 0

In [22]:
X_c1.shape[0]

498

In [18]:
len(X_c1) ,len(X_c2) # distribution of target 

(498, 502)

In [19]:
class NaiveBayes:

    def fit(self, X, y):
        n_samples, n_features = X.shape
        self._classes = np.unique(y)
        n_classes = len(self._classes)

        # calculate mean, var, and prior for each class
        self._mean = np.zeros((n_classes, n_features), dtype=np.float64)
        self._var = np.zeros((n_classes, n_features), dtype=np.float64)
        self._priors =  np.zeros(n_classes, dtype=np.float64)

        for idx, c in enumerate(self._classes):
            X_c = X[y==c]
            self._mean[idx, :] = X_c.mean(axis=0)
            self._var[idx, :] = X_c.var(axis=0)
            self._priors[idx] = X_c.shape[0] / float(n_samples)

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        posteriors = []

        # calculate posterior probability for each class
        for idx, c in enumerate(self._classes):
            prior = np.log(self._priors[idx])
            posterior = np.sum(np.log(self._pdf(idx, x)))
            posterior = prior + posterior
            posteriors.append(posterior)
            
        # return class with highest posterior probability
        return self._classes[np.argmax(posteriors)]
            
    # getting probability distribution function for class 
    def _pdf(self, class_idx, x):
        mean = self._mean[class_idx]
        var = self._var[class_idx]
        numerator = np.exp(- (x-mean)**2 / (2 * var))
        denominator = np.sqrt(2 * np.pi * var)
        return numerator / denominator

In [20]:
def accuracy(y_true, y_pred):
    accuracy = np.sum(y_true == y_pred) / len(y_true)
    return accuracy

In [21]:
nb = NaiveBayes()
nb.fit(X_train, y_train)
predictions = nb.predict(X_test)

print("Naive Bayes classification accuracy", accuracy(y_test, predictions))

Naive Bayes classification accuracy 0.965
