In [2]:
import numpy as np
print(np.__version__)

1.18.1


In [4]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [11]:
a.shape ,a.dtype

((3,), dtype('int32'))

In [12]:
a.ndim,a.size,a.itemsize

(1, 3, 4)

In [13]:
a[0]

1

In [14]:
a[0]=10
a

array([10,  2,  3])

In [15]:
b = a*np.array([2,0,2])
b

array([20,  0,  6])

### diff between array ans list 

In [23]:
l =[1,2,3]
a = np.array([l])


In [24]:
l.append(4)
l

[1, 2, 3, 4]

In [25]:
l = l+[5]
print(l)

[1, 2, 3, 4, 5]


In [26]:
a1= a+np.array([5])# broadcasting
a1

array([[6, 7, 8]])

In [28]:
a2 = a+np.array([1,2,3])
a2

array([[2, 4, 6]])

In [29]:
l2 = l*2
l2

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [30]:
a3 = a*2
a3

array([[2, 4, 6]])

In [31]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081]])

In [37]:
##dot product
l1 =[1,2,3]
l2 =[5,6,7]
dot = 0
for i in range(len(l1)):
    dot += l1[i]*l2[i]
print(dot)

38


In [38]:
a1 = np.array(l1)
a2 = np.array(l2)
dot = np.dot(a1,a2)
dot

38

In [39]:
sum1 = a1*a2# element wise operation
print(sum1)
dot  = np.sum(sum1)
print(dot)

[ 5 12 21]
38


In [40]:
dot = a1@a2
print(dot)

38


### speed test 

In [41]:
from timeit import default_timer as timer

a = np.random.randn(1000)
b = np.random.randn(1000)

A = list(a)
B = list(b)

T = 1000

def dot1():
    dot = 0
    for i in range(len(A)):
        dot += A[i]*B[i]
    return dot

def dot2():
    return np.dot(a,b)

In [43]:
start = timer()
for t in range(T):
    dot1()
end = timer()
t1 = end-start

start = timer()
for t in range(T):
    dot2()
end = timer()
t2 = end-start

print('Time with lists:', t1)
print('Time with nparray:', t2)
print('Ratio', t1/t2)

Time with lists: 0.6753521000000546
Time with nparray: 0.003194299999904615
Ratio 211.42413048875224


###  nd arrays = multidimensional arrays

In [44]:
# nd arrays = multidimensional arrays
# (matrix class exists but not recommended to use)
a = np.array([[1,2], [3,4]])
print(a)
print(a.shape)

[[1 2]
 [3 4]]
(2, 2)


In [45]:
# row first, then columns
print(a[0])
print(a[0][0])
print(a[0,0])

[1 2]
1
1


In [46]:
# slicing
print(a[:,0]) # all rows in col 0
print(a[0,:]) # all columns in row 0

[1 3]
[1 2]


In [47]:
# transpose
print(a.T)

[[1 3]
 [2 4]]


In [48]:
# matrix multiplication
b = np.array([[3, 4], [5,6]])
c = a.dot(b)
print(c)
d = a * b # elementwise multiplication
print(d)

[[13 16]
 [29 36]]
[[ 3  8]
 [15 24]]


In [49]:
# inner dimensions must match!
b = np.array([[1,2,3], [4,5,6]])
#c = a.dot(b.T)
#printc)


ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [50]:
# determinant
c = np.linalg.det(a)
print(c)


-2.0000000000000004


In [52]:
# inverse
c = np.linalg.inv(a)
print(c)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [53]:
# diag
c = np.diag(a)
print(c)

[1 4]


In [54]:
# diag on a vector returns diagonal matrix (overloaded function)
c = np.diag([1,4])
print(c)

[[1 0]
 [0 4]]


### Array indexing
#### Slicing: Similar to Python lists, numpy arrays can be sliced.
#### Since arrays may be multidimensional, you must specify a slice for each 

In [55]:

# dimension of the array:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a)

# Integer array indexing
b = a[0,1]
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2


In [56]:
# Slicing
row0 = a[0,:]
print(row0)

col0 = a[:, 0]
print(col0)

[1 2 3 4]
[1 5 9]


In [57]:
slice_a = a[0:2,1:3]
print(slice_a)

[[2 3]
 [6 7]]


In [58]:
# indexing starting from the end: -1, -2 etc...
last = a[-1,-1]
print(last)

12


In [59]:
# Boolean indexing:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [60]:
# same shape with True or False for the condition
bool_idx = a > 2
print(bool_idx)

[[False False]
 [ True  True]
 [ True  True]]


In [61]:
# note: this will be a rank 1 array!
print(a[bool_idx])

[3 4 5 6]


In [62]:
# We can do all of the above in a single concise statement:
print(a[a > 2])

[3 4 5 6]


In [63]:
# np.where(): same size with modified values
b = np.where(a>2, a, -1)
print(b)


[[-1 -1]
 [ 3  4]
 [ 5  6]]


In [65]:
# fancy indexing: access multiple indices at once
a = np.array([10,19,30,41,50,61])
print(a)
b = a[[1,3,5]]
print(b)

[10 19 30 41 50 61]
[19 41 61]


In [66]:
even = np.argwhere(a%2==0).flatten()
print(even)
a_even = a[even]
print(a_even)

[0 2 4]
[10 30 50]


In [67]:
# reshape
a = np.arange(1, 7)
print(a)

[1 2 3 4 5 6]


In [68]:
b = a.reshape((2, 3)) # error if shape cannot be used
print(b)

[[1 2 3]
 [4 5 6]]


In [69]:
c = a.reshape((3, 2)) # 3 rows, 2 columns
print(c)

[[1 2]
 [3 4]
 [5 6]]


##### newaxis

In [72]:
# newaxis is used to create a new axis in the data
# needed when model require the data to be shaped in a certain manner
print(a.shape)
d = a[np.newaxis, :]
print(d)
print(d.shape)

(6,)
[[1 2 3 4 5 6]]
(1, 6)


In [73]:
e = a[:, np.newaxis]
print(e)
print(e.shape)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
(6, 1)


#### concatenation

In [78]:
a = np.array([[1, 2], [3, 4]])
print(a)
b = np.array([[5, 6]])
print(b)

[[1 2]
 [3 4]]
[[5 6]]


![img.png](https://i.stack.imgur.com/h1alT.jpg)

In [79]:
c = np.concatenate((a, b), axis=None)
print(c)

[1 2 3 4 5 6]


In [80]:
d = np.concatenate((a, b), axis=0)
print(d)

[[1 2]
 [3 4]
 [5 6]]


In [81]:
b.T

array([[5],
       [6]])

In [82]:
e = np.concatenate((a, b.T), axis=1)
print(e)

[[1 2 5]
 [3 4 6]]


In [83]:
# hstack: Stack arrays in sequence horizontally (column wise). needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.hstack((a,b))
print(c)

[1 2 3 4 5 6 7 8]


In [84]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.hstack((a,b))
print(c)

[[1 2 5 6]
 [3 4 7 8]]


In [85]:
# vstack: Stack arrays in sequence vertically (row wise). needs a tuple
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.vstack((a,b))
print(c)

[[1 2 3 4]
 [5 6 7 8]]


In [86]:
a = np.array([[1,2], [3,4]])
b = np.array([[5,6], [7,8]])
c = np.vstack((a,b))
print(c)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


####  broadcasting

##### Broadcasting is a powerful mechanism that allows numpy to work with arrays of different shapes when performing arithmetic operations.

In [88]:


# Broadcasting is a powerful mechanism that allows numpy to work with arrays of 
# different shapes when performing arithmetic operations.
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
print(x)
print(v)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 0 1]


In [89]:
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [90]:
# data science functions and axes
a = np.array([[7,8,9,10,11,12,13], [17,18,19,20,21,22,23]])
print(a)
print(a.sum(axis=None)) # overall sum
print(a.sum())
print(a.sum(axis=0)) # along the rows -> 1 sum entry for each column
print(a.sum(axis=1)) # along the columns -> 1 sum entry for each row

[[ 7  8  9 10 11 12 13]
 [17 18 19 20 21 22 23]]
210
210
[24 26 28 30 32 34 36]
[ 70 140]


In [91]:
print(a.mean(axis=None)) # overall mean
print(a.mean())
print(a.mean(axis=0)) # along the rows -> 1 mean entry for each column
print(a.mean(axis=1)) # along the columns -> 1 mean entry for each row

# some more: std, var, min, max

15.0
15.0
[12. 13. 14. 15. 16. 17. 18.]
[10. 20.]


In [92]:

# datatypes
# https://numpy.org/devdocs/user/basics.types.html
# Let numpy choose the datatype
x = np.array([1, 2])
print(x.dtype)

# Let numpy choose the datatype
x = np.array([1.0, 2.0])
print(x.dtype)

# Force a particular datatype, how many bits (how precise)
x = np.array([1, 2], dtype=np.int64) # 8 bytes
print(x.dtype)

x = np.array([1, 2], dtype=np.float32) # 4 bytes
print(x.dtype)

int32
float64
int64
float32


In [95]:
# copy
a = np.array([1,2,3])
b = a # only copies reference!
b[0] = 42
print(a)
print(b)

[42  2  3]
[42  2  3]


In [96]:
a = np.array([1,2,3])
b = a.copy() # actual copy!
b[0] = 42
print(a)
print(b)

[1 2 3]
[42  2  3]


In [97]:
# generating data
a = np.zeros((2,3)) # size as tuple
b = np.ones((2,3))
print(a)
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [98]:
# specific value
c = 5 * np.ones((3,3))
print(c)
c = np.full((3,3),5.0)
print(c)
# identity
d = np.eye(3) #3x3
print(d)

[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [99]:
# arange
e = np.arange(10)
print(e)

# linspace
f = np.linspace(0, 10, 5)
print(f)

[0 1 2 3 4 5 6 7 8 9]
[ 0.   2.5  5.   7.5 10. ]


####  random numbers

In [105]:


a = np.random.random((3,2)) # uniform 0-1 distribution
print(a)
b = np.random.randn(3,2) # normal/Gaussian distribution, mean 0 and unit variance
# no tuple as shape here! each dimension one argument
print(b)

[[0.33775532 0.2272306 ]
 [0.08207566 0.30255801]
 [0.00519897 0.99571264]]
[[ 0.67619658 -0.42322606]
 [-1.22620179 -0.22258763]
 [-1.20283154  0.86612326]]


In [106]:
R = np.random.randn(10000)
print(R.mean(), R.var(), R.std())

-0.006681892238034454 1.0070204608060307 1.0035040910758812


In [107]:
R = np.random.randn(10, 3)
print(R.mean()) # mean of whole array

0.02427028683556919


In [108]:
# random integer, low,high,size; high is exclusive
R = np.random.randint(3,10,size=(3,3)) # if we only pass one parameter, then from 0-x
print(R)

[[9 9 8]
 [7 6 4]
 [4 5 7]]


In [109]:
# with integer is between 0 up to integer exclusive
c = np.random.choice(7, size=10)
print(c)
# with an array it draws random values from this array
d = np.random.choice([1,2,3,4], size=8)
print(d)

[3 3 2 3 0 3 4 1 6 3]
[2 1 4 1 4 2 3 1]


#### Eigenvalues

In [110]:
a = np.array([[1,2], [3,4]])
eigenvalues, eigenvectors = np.linalg.eig(a)
# Note: use eigh if your matrix is symmetric (faster)
print(eigenvalues)
print(eigenvectors) # column vectors
print(eigenvectors[:,0]) # column 0 corresponding to eigenvalue[0]

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]
[-0.82456484  0.56576746]


In [111]:
# verify: e-vec * e-val = A * e-vec
d = eigenvectors[:,0] * eigenvalues[0]
e = a @ eigenvectors[:, 0]
print(d, e)
print(d == e) # numerical issues

# correct way to compare matrix
print(np.allclose(d,e))

[ 0.30697009 -0.21062466] [ 0.30697009 -0.21062466]
[ True False]
True


##### solve linear system:

 x1+x2=2200
    
 1.5 x1 + 4 x2 = 5050

2 equations and 2 unknowns

In [112]:

A = np.array([[1, 1], [1.5, 4]])
b = np.array([2200,5050])

# Ax = b <=> x = A-1 b

# But: inverse is slow and less accurate
x = np.linalg.inv(A).dot(b) # not recommended
print(x)
x = np.linalg.solve(A,b) # good
print(x)

[1500.  700.]
[1500.  700.]


In [113]:
# 1) load with np.loadtxt()
# skiprows=1
data = np.loadtxt(FILE_NAME, delimiter=",",dtype=np.float32)
print(data.shape, data.dtype)

# 2) load with np.genfromtxt()
# skip_header=0, missing_values="---", filling_values=0.0
data = np.genfromtxt(FILE_NAME, delimiter=",", dtype=np.float32)
print(data.shape)

NameError: name 'FILE_NAME' is not defined